import {
  Activity,
  BarChart3,
  Bell,
  Building2,
  CalendarClock,
  CalendarDays,
  CheckCircle2,
  Clapperboard,
  Clock,
  Coins,
  Euro,
  Eye,
  FileText,
  Flame,
  Gift,
  Handshake,
  Heart,
  Instagram,
  Layers,
  Lightbulb,
  Link2,
  ListChecks,
  MessageCircle,
  MousePointerClick,
  Music2,
  PackageOpen,
  PiggyBank,
  Radio,
  Receipt,
  Rocket,
  ShoppingCart,
  Sparkles,
  Star,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Truck,
  Users,
  Video,
  Wallet,
  Youtube,
  type LucideIcon,
} from 'lucide-react';

/**
 * Les icônes qu'on peut donner à un bloc du dashboard. Un **jeu fermé** : l'API ne stocke
 * qu'une clé, et une icône libre n'aurait aucune équivalence côté serveur — même parti
 * pris que `EXTERNAL_APP_ICONS`. Une clé inconnue (retirée d'ici) retombe sur l'icône
 * d'origine du bloc.
 *
 * Ce fichier n'exporte aucun composant (`react-refresh/only-export-components`).
 */
export const WIDGET_ICONS: Record<string, { label: string; icon: LucideIcon }> = {
  wallet: { label: 'Portefeuille', icon: Wallet },
  euro: { label: 'Euro', icon: Euro },
  coins: { label: 'Pièces', icon: Coins },
  piggy: { label: 'Tirelire', icon: PiggyBank },
  receipt: { label: 'Reçu', icon: Receipt },
  trending: { label: 'Tendance', icon: TrendingUp },
  chart: { label: 'Graphique', icon: BarChart3 },
  activity: { label: 'Activité', icon: Activity },
  eye: { label: 'Vues', icon: Eye },
  users: { label: 'Abonnés', icon: Users },
  heart: { label: 'Cœur', icon: Heart },
  message: { label: 'Commentaire', icon: MessageCircle },
  clock: { label: 'Horloge', icon: Clock },
  timer: { label: 'Chrono', icon: Timer },
  video: { label: 'Vidéo', icon: Video },
  clapperboard: { label: 'Clap', icon: Clapperboard },
  radio: { label: 'Diffusion', icon: Radio },
  youtube: { label: 'YouTube', icon: Youtube },
  instagram: { label: 'Instagram', icon: Instagram },
  music: { label: 'Musique', icon: Music2 },
  gift: { label: 'Cadeau', icon: Gift },
  package: { label: 'Colis', icon: PackageOpen },
  truck: { label: 'Livraison', icon: Truck },
  handshake: { label: 'Partenariat', icon: Handshake },
  link: { label: 'Lien', icon: Link2 },
  click: { label: 'Clic', icon: MousePointerClick },
  cart: { label: 'Vente', icon: ShoppingCart },
  trophy: { label: 'Trophée', icon: Trophy },
  star: { label: 'Étoile', icon: Star },
  sparkles: { label: 'Étincelles', icon: Sparkles },
  flame: { label: 'Flamme', icon: Flame },
  target: { label: 'Objectif', icon: Target },
  rocket: { label: 'Fusée', icon: Rocket },
  calendar: { label: 'Calendrier', icon: CalendarDays },
  deadline: { label: 'Échéance', icon: CalendarClock },
  checks: { label: 'Tâches', icon: ListChecks },
  check: { label: 'Validé', icon: CheckCircle2 },
  bell: { label: 'Alerte', icon: Bell },
  idea: { label: 'Idée', icon: Lightbulb },
  file: { label: 'Document', icon: FileText },
  building: { label: 'Société', icon: Building2 },
  layers: { label: 'Couches', icon: Layers },
};
